trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
    displayName: 'Instalar Python 3.11'

  - task: UseNode@1
    inputs:
      version: '18.x'
    displayName: 'Instalar Node.js 18'

  - script: |